---
- name: Deploy Dockerized Application
  hosts: app_servers
  become: yes
  vars:
    app_dir: /opt/devops-app
  vars_files:
    - vars.yml

  tasks:
    # Install required packages
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
        state: present

    # Install Docker
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # Start and enable Docker
    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      
    # Clone repository and run docker-compose
    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        
    - name: Create .env file
      copy:
        dest: "{{ app_dir }}/.env"
        content: "{% for key, value in app_env.items() %}{{ key }}={{ value }}\n{% endfor %}"
      
    - name: Build with Docker Compose
      command: docker-compose build
      args:
        chdir: "{{ app_dir }}"
      async: 1800  # 30 minutes timeout
      poll: 30     # Check every 30 seconds
        
    - name: Run with Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ app_dir }}"
      async: 1800  # 30 minutes timeout
      poll: 30     # Check every 30 seconds